[[items]]
display_name = "StatTrak™ Karambit | Tiger Tooth (Factory New)5"
url = "https://buff.163.com/goods/43766?from=market#tab=selling"
alarm_price = 5000
[[items]]
display_name = "StatTrak™ Karambit | Tiger Tooth (Factory New)4"
url = "https://buff.163.com/goods/43766?from=market#tab=selling"
alarm_price = 5000
[[items]]
display_name = "StatTrak™ Karambit | Tiger Tooth (Factory New)3"
url = "https://buff.163.com/goods/43766?from=market#tab=selling"
alarm_price = 5000
[[items]]
display_name = "StatTrak™ Karambit | Tiger Tooth (Factory New)2"
url = "https://buff.163.com/goods/43766?from=market#tab=selling"
alarm_price = 5000
[[items]]
display_name = "StatTrak™ Karambit | Tiger Tooth (Factory New)1"
url = "https://buff.163.com/goods/43766?from=market#tab=selling"
alarm_price = 5000
